"""Updating audit_log to SQLAlchemy 2.0 syntax to match other tables

Revision ID: 769fc9c97e25
Revises: 3e6188f53510
Create Date: 2026-01-29 16:02:09.486570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '769fc9c97e25'
down_revision: Union[str, Sequence[str], None] = '3e6188f53510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
