"""added_score_method_to_parameters_table

Revision ID: 2dbb4eeaac05
Revises: 6695817e32fc
Create Date: 2026-01-13 10:37:42.264835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbb4eeaac05'
down_revision: Union[str, Sequence[str], None] = '6695817e32fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('score_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameters', 'score_method')
    # ### end Alembic commands ###
