"""Add Auditlog Table

Revision ID: 8af9fea9a13c
Revises: 0ab2f52b43df
Create Date: 2026-01-24 21:08:38.081665

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '8af9fea9a13c'
down_revision: Union[str, Sequence[str], None] = '0ab2f52b43df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
