"""added exclusions to recommendations table

Revision ID: 6695817e32fc
Revises: 47d1e9a4d7ff
Create Date: 2026-01-11 23:24:40.089907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6695817e32fc'
down_revision: Union[str, Sequence[str], None] = '47d1e9a4d7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('exclusions', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'exclusions')
    # ### end Alembic commands ###
